# Generated by Django 3.0.6 on 2020-05-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_email',
            field=models.CharField(max_length=300),
        ),
    ]
